### ISSUE TITLE
Problème mauvais SSI

### ISSUE THREAD

**Issue by ghost** [3rd-KaTZe/Link#5]
J'ai eu un souci en jouant avec le Link, j'ai cru que j'avais tout cassé mais j'étais sur une ancienne version du SSI (j'ai découvert depuis que SIOC conserve son sioc.ini dans le VirtualStore, celui qui est dans ProgramFiles est juste un attrape-couillon ... T_T )

```
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\threading.py", line 869, in run
    self._target(*self._args, **self._kwargs)
  File "F:/DEV/Link_vKatze/helo_link.py", line 445, in sioc_client
    KTZmain.Sioc_Dico = sbr_string.Sioc_Read(KTZmain.msgSioc)
  File "F:\DEV\Link_vKatze\sbr_string.py", line 42, in Sioc_Read
    ST[int(elementS[0])]=int(elementS[1])
IndexError: list index out of range
```

Cfr commit lié

**Comment by ghost** [comment]
Bon SmartGit n'en fait qu'à sa tête je vais arrêter de me battre contre des moulins, le problème qui nous intéresse se trouve dans 'helo_link.py' à la ligne 445. Désolé pour le bordel, et vive la ligne de commande en fait ...

**Comment by ghost** [comment]
Corrigé
